---
title: "DEI ACS PUMS Data Checks - Indicator 2: Business Ownership"
author: "Kaitlan Wong"
format: html
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidycensus)
library(tidyverse)
library(readxl)
library(writexl)
library(dplyr)
```

See https://walker-data.com/census-r/analyzing-census-microdata.html

Get 2021 ACS PUMS data.

```{r}
# Get ACS data
pums21 <- get_pums(
  variables = c("AGEP", "RAC1P", "HISP", "PUMA", "COW"),
  state = "TX",
  survey = "acs1",
  year = 2021,
  recode = TRUE,
)

# View data
head(pums21)
```

Filter for Dallas PUMAs and mutate variables

```{r}
# Filter for Dallas PUMAs and working-age adults
data21 <- pums21 %>%
  filter(PUMA %in% c("02304", "02305", "02306", "02307", "02309", "02310", "02311", "02312", "02313", "02314", "02315", "02316", "02319", "01901", "02001"),
         AGEP >= 25 & AGEP <= 64) %>%
  # recode race/ethnicity
  mutate(race_eth = case_when(
     HISP != "01" ~ "Hispanic",
    HISP == "01" & RAC1P == "1" ~ "White, non-Hispanic",
    HISP == "01" & RAC1P == "2" ~ "Black, non-Hispanic",
    HISP == "01" & RAC1P %in% c("3","4","5") ~ "AIAN, non-Hispanic",
    HISP == "01" & RAC1P %in% c("6","7") ~ "Asian or Pacific Islander, non-Hispanic",
    HISP == "01" & RAC1P %in% c("8","9") ~ "Other, non-Hispanic",
    TRUE ~ NA_character_)
  ) %>%
   mutate(self_employ = case_when(
     COW %in% c("6","7") ~ "Self-Employed",
     TRUE ~ "Not Self-Employed")
   )
     
```

Summarize data using person weight.

```{r}
# Calculate summary statistics
summary21 <- data21 %>%
  group_by(race_eth) %>%
  summarize(
    count = sum(PWGTP[self_employ == "Self-Employed"]),
    prop = sum(PWGTP[self_employ == "Self-Employed"]) / sum(PWGTP)
  )

summary21
```

Repeat steps for 2019 data.

```{r}
# Get ACS data
pums19 <- get_pums(
  variables = c("AGEP", "RAC1P", "HISP", "PUMA", "COW"),
  state = "TX",
  survey = "acs1",
  year = 2019,
  recode = TRUE,
)

# View data
head(pums19)
```

```{r}
# Filter for Dallas PUMAs and working-age adults
data19 <- pums19 %>%
  filter(PUMA %in% c("02304", "02305", "02306", "02307", "02309", "02310", "02311", "02312", "02313", "02314", "02315", "02316", "02319", "01901", "02001"),
         AGEP >= 25 & AGEP <= 64) %>%
  # recode race/ethnicity
  mutate(race_eth = case_when(
     HISP != "01" ~ "Hispanic",
    HISP == "01" & RAC1P == "1" ~ "White, non-Hispanic",
    HISP == "01" & RAC1P == "2" ~ "Black, non-Hispanic",
    HISP == "01" & RAC1P %in% c("3","4","5") ~ "AIAN, non-Hispanic",
    HISP == "01" & RAC1P %in% c("6","7") ~ "Asian or Pacific Islander, non-Hispanic",
    HISP == "01" & RAC1P %in% c("8","9") ~ "Other, non-Hispanic",
    TRUE ~ NA_character_)
  ) %>%
   mutate(self_employ = case_when(
     COW %in% c("6","7") ~ "Self-Employed",
     TRUE ~ "Not Self-Employed")
   )

# Calculate summary statistics
summary19 <- data19 %>%
  group_by(race_eth) %>%
  summarize(
    count = sum(PWGTP[self_employ == "Self-Employed"]),
    prop = sum(PWGTP[self_employ == "Self-Employed"]) / sum(PWGTP)
  )

summary19
```

Export tables to Excel.

```{r}
# Export tables to Excel

write_xlsx(list("2021" = summary21, "2019" = summary19), "02_Business_Ownership.xlsx")
```
