---
title: "DEI ACS PUMS Data Checks - Indicator 28: Housing Cost Burden"
author: "Kaitlan Wong"
format: html
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidycensus) 
library(tidyverse) 
library(readxl) 
library(writexl) 
library(dplyr)
```

#### See <https://walker-data.com/census-r/analyzing-census-microdata.html> for guidance on using tidycensus to get ACS PUMS

#### ACS PUMS Data Documentation: <https://www.census.gov/programs-surveys/acs/microdata/documentation.html>

#### 2021 ACS Data Dictionary: <https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMS_Data_Dictionary_2021.pdf>

Get 2021 ACS PUMS data.

```{r}
# Get ACS data
# Note: OCPIP is defined as "Selected monthly owner costs as a percentage of household income during the past 12 months". GRPIP is defined as "Gross rent as a percentage of household income past 12 months"
pums21 <- get_pums(
  variables = c("AGEP", "RAC1P", "HISP", "PUMA", "GRPIP", 'OCPIP'),
  state = "TX",
  survey = "acs1",
  year = 2021,
  recode = TRUE,
)

# View data
head(pums21)
```

Filter for Dallas PUMAs and mutate variables

```{r}
# Filter for Dallas PUMAs
data21 <- pums21 %>%
  filter(PUMA %in% c("02304", "02305", "02306", "02307", "02309", "02310", "02311", "02312", "02313", "02314", "02315", "02316", "02319", "01901", "02001")) %>%
  # recode race/ethnicity
  mutate(race_eth = case_when(
    HISP != "01" ~ "Hispanic",
    HISP == "01" & RAC1P == "1" ~ "White, non-Hispanic",
    HISP == "01" & RAC1P == "2" ~ "Black, non-Hispanic",
    HISP == "01" & RAC1P %in% c("3","4","5") ~ "AIAN, non-Hispanic",
    HISP == "01" & RAC1P %in% c("6","7") ~ "Asian or Pacific Islander, non-Hispanic",
    HISP == "01" & RAC1P %in% c("8","9") ~ "Other, non-Hispanic",
    TRUE ~ NA_character_)
  ) %>%
  # recode home cost burden variable
  mutate(burdened = case_when(
    GRPIP > 30 | OCPIP > 30 ~ "Housing Cost Burdened",
    GRPIP == 0 | OCPIP == 0 ~ "NA",
    TRUE ~ "Not Housing Cost Burdened")
   )
```

Create table of counts and %s using household weight variable.

```{r}
# Calculate # and % of households that spend over 30% of houshold income on rent or owner costs by race/ethnicity of householder
summary21 <- data21 %>%
  group_by(race_eth) %>%
  summarize(
    count = sum(WGTP[burdened == "Housing Cost Burdened"], na.rm = TRUE),
    prop = sum(WGTP[burdened == "Housing Cost Burdened"], na.rm = TRUE) / sum(WGTP)
  )

summary21


# Calculate total # and % of households that spend over 30% of houshold income on rent or owner costs
summary_all21 <- data21 %>%
  summarize(
    count = sum(WGTP[burdened == "Housing Cost Burdened"], na.rm = TRUE),
    prop = sum(WGTP[burdened == "Housing Cost Burdened"], na.rm = TRUE) / sum(WGTP, na.rm = TRUE)
  )

summary_all21
```

Repeat steps for 2019 data.

```{r}
# Get ACS data
pums19 <- get_pums(
  variables = c("AGEP", "RAC1P", "HISP", "PUMA", "GRPIP", 'OCPIP'),
  state = "TX",
  survey = "acs1",
  year = 2019,
  recode = TRUE,
)

# View data
head(pums19)
```

```{r}
# Filter for Dallas PUMAs
data19 <- pums19 %>%
  filter(PUMA %in% c("02304", "02305", "02306", "02307", "02309", "02310", "02311", "02312", "02313", "02314", "02315", "02316", "02319", "01901", "02001")) %>%
  # recode race/ethnicity
  mutate(race_eth = case_when(
    HISP != "01" ~ "Hispanic",
    HISP == "01" & RAC1P == "1" ~ "White, non-Hispanic",
    HISP == "01" & RAC1P == "2" ~ "Black, non-Hispanic",
    HISP == "01" & RAC1P %in% c("3","4","5") ~ "AIAN, non-Hispanic",
    HISP == "01" & RAC1P %in% c("6","7") ~ "Asian or Pacific Islander, non-Hispanic",
    HISP == "01" & RAC1P %in% c("8","9") ~ "Other, non-Hispanic",
    TRUE ~ NA_character_)
  ) %>%
  # recode home cost burden variable
  mutate(burdened = case_when(
    GRPIP > 30 | OCPIP > 30 ~ "Housing Cost Burdened",
    GRPIP == 0 | OCPIP == 0 ~ "NA",
    TRUE ~ "Not Housing Cost Burdened")
   )


# Calculate total # and % of households that spend over 30% of houshold income on rent or owner costs by race/ethnicity of houesholder
summary19 <- data19 %>%
  group_by(race_eth) %>%
  summarize(
    count = sum(WGTP[burdened == "Housing Cost Burdened"], na.rm = TRUE),
    prop = sum(WGTP[burdened == "Housing Cost Burdened"], na.rm = TRUE) / sum(WGTP)
  )

summary19


# Calculate total # and % of households that spend over 30% of houshold income on rent or owner costs
summary_all19 <- data19 %>%
  summarize(
    count = sum(WGTP[burdened == "Housing Cost Burdened"], na.rm = TRUE),
    prop = sum(WGTP[burdened == "Housing Cost Burdened"], na.rm = TRUE) / sum(WGTP, na.rm = TRUE)
  )

summary_all19
```

```{r}
# Export tables to Excel

write_xlsx(list("2021" = summary21, "2019" = summary19), "28_Housing Cost Burden.xlsx")
```
